[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
